##############################################################################
# IMXRT blinky makefile rules
#
#

all:
	@echo
	@echo === Building for IMXRT1021_Eval_brd  ===============================
	+@make --no-print-directory -f make/imxrt1020.make all
	@echo ====================================================================


clean:
	@echo
	+@make --no-print-directory -f make/imxrt1020.make clean
	@echo

#
##############################################################################
